# OTC Markets
We wraped the data from [OTC Markets.](https://www.otcmarkets.com/market-activity/current-market/ALL/active/dollarVolume) Then, we were fail to wrap all of data (18524 companies) by using splinter "click_link" because the MORE button design of this website is a Javescript which would be triggered when user click it. Therefore, we decided to click MORE button by ourselves to show all of data and wrap it.

In [1]:
from splinter import Browser
from urllib.request import urlopen
from bs4 import BeautifulSoup
import requests
import pandas as pd
from sqlalchemy import create_engine
import pymysql

In [22]:
executable_path = {'executable_path': '/usr/local/bin/chromedriver'}
browser = Browser('chrome', **executable_path, headless=False)
url = "https://www.otcmarkets.com/market-activity/current-market/ALL/active/dollarVolume"
browser.visit(url)

In [3]:
#We click MORE button for several times to get all of data.
html = browser.html
soup = BeautifulSoup(html,'html.parser')

In [4]:
#Wrap the whole table content.
OTC_market_soup = soup.find('table', class_='_1DoSj9nrVo')
#Change bs4 object into html format
html_content = OTC_market_soup.prettify()

In [5]:
#Using Pandas to read html
OTC_market_list = pd.read_html(html_content)

In [7]:
#Convert it to DataFrame and rename columns name
OTC_market_table = OTC_market_list[0]
OTC_market_table.rename(columns={"Symbol  Sym":"company","Price  Price":"price",
                                 "% Change  % Change": "change_percent", "$ Vol  $ Vol": "vol",
                                 "Share Vol  Share Vol":"share_vol","Trades  Trades":"trades"},inplace=True)
OTC_market_table.head(10)

  company     price  change_percent      vol  share_vol  trades
0   CSGKF   13.3100            0.23  2938102     222533      50
1   CURLF   10.7800            8.78  1990604     186077     494
2   TCEHY   49.4100            0.35  1812836      36682     208
3   GLCNF    3.9966           -0.16  1799338     450217       6
4   CMXHF  140.9500            0.00  1592338      11292       3
5   OGRMF    7.4900            0.54  1484344     196929     506
6   SFTBY   53.2600            0.15  1373286      25790      60
7   CSLLY   70.6800           -0.92   860877      12211       6
8    GBTC    6.7100            1.51   731449     109399     117
9   RHHBY   32.9360           -0.38   716182      21690      60

In [8]:
#Wrap the icon image link from website in order to identify which Symbol it is.
#Find all of icon image link
icon_list = OTC_market_soup.find_all("div",class_="_2_IqcDGekT")
symbol_icon = []
for x in icon_list:
    #Only take symbol portion from link
    symbol_icon.append(x.img["src"][12:14])

In [9]:
#Combine symbol data into OTC Market
OTC_market_table["symbol"] = symbol_icon
OTC_market_table.head()

  company     price  change_percent      vol  share_vol  trades symbol
0   CSGKF   13.3100            0.23  2938102     222533      50     ps
1   CURLF   10.7800            8.78  1990604     186077     494     qx
2   TCEHY   49.4100            0.35  1812836      36682     208     ps
3   GLCNF    3.9966           -0.16  1799338     450217       6     ps
4   CMXHF  140.9500            0.00  1592338      11292       3     ps

We only chose QX and QB symbol.

In [10]:
OTC_QX_QB = OTC_market_table.loc[(OTC_market_table.symbol == "qx") | (OTC_market_table.symbol == "qb"),:]
OTC_QX_QB.reset_index(drop=True,inplace=True)
OTC_QX_QB.head(10)

  company    price  change_percent      vol  share_vol  trades symbol
0   CURLF  10.7800            8.78  1990604     186077     494     qx
1   OGRMF   7.4900            0.54  1484344     196929     506     qx
2    GBTC   6.7100            1.51   731449     109399     117     qx
3   RHHBY  32.9360           -0.38   716182      21690      60     qx
4   ACRGF  22.6113            1.58   497366      22053      60     qx
5   TGODF   3.4100            1.79   448388     131052     127     qx
6   GTBIF  14.9706            0.39   367509      24613     105     qx
7    CVSI   5.2100           -1.14   365058      69336     103     qb
8   VGWCF   3.2500           -3.56   309490      93623     144     qb
9   AVMXY   4.9300           -6.10   294467      59678      67     qx

In [103]:
OTC_QX_QB.to_csv("part_qx_qb.csv")

## Connect to local database

In [13]:
rds_connection_string = "root:Pega#123456@127.0.0.1/ETL_Market"
engine = create_engine(f'mysql://{rds_connection_string}')

In [14]:
#Check for tables
engine.table_names()

['OTC_company']

In [16]:
#Use soup to scrape web, then use pandas converted DataFrame into database
OTC_QX_QB.to_sql(name='OTC_company', con=engine, if_exists='append', index=False)

In [17]:
#Confirm data has been added by querying the customer_name table
pd.read_sql_query('select * from OTC_company', con=engine)

    id company     price  change_percent      vol  share_vol  trades symbol
0    1   CURLF   10.7800            8.78  1990604     186077     494     qx
1    2   OGRMF    7.4900            0.54  1484344     196929     506     qx
2    3    GBTC    6.7100            1.51   731449     109399     117     qx
3    4   RHHBY   32.9360           -0.38   716182      21690      60     qx
4    5   ACRGF   22.6113            1.58   497366      22053      60     qx
5    6   TGODF    3.4100            1.79   448388     131052     127     qx
6    7   GTBIF   14.9706            0.39   367509      24613     105     qx
7    8    CVSI    5.2100           -1.14   365058      69336     103     qb
8    9   VGWCF    3.2500           -3.56   309490      93623     144     qb
9   10   AVMXY    4.9300           -6.10   294467      59678      67     qx
10  11   RHHVF  261.6001           -0.32   276192       1055      46     qx
11  12   KHRNF    2.5240           -5.66   290997     115144     101     qb
12  13   RHHVF  261.6001           -0.32   276192       1055      46     qx
13  14   HRVSF    8.7455            0.29   235828      26971      89     qx
14  15   CRLBF   13.0996            1.39   235138      17942      59     qx
15  16    KSHB    5.3200           -0.75   201945      37878     114     qb
16  17   CWBHF   19.5523            1.57   197315      10175      93     qx
17  18    FNMA    2.4900            0.81   189876      76702     106     qb
18  19   SVVTF    1.9945           -5.75   185783      96333     130     qb
19  20   SRUTF    0.6800            4.13   185353     272776     115     qb
20  21   ITHUF    4.8450            0.31   184661      38036      74     qx
21  22    FMCC    2.4200            0.83   176660      73575     154     qb
22  23   DYMEF    2.1200           12.77   150177      72940      89     qb
23  24   DANOY   16.2500            0.18   148115       9126      10     qx
24  25   PLNHF    2.3600           -1.95   134455      56569      92     qb
25  26    FRLI    2.3600            2.16   124883      52643      66     qb
26  27   IMBBY   31.4740           -1.64   116394       3679      26     qx
27  28   ELLXF    3.1200           -1.89   114063      36235      64     qx
28  29   FNMAS   11.0000           -0.72   111352      10121      49     qb
29  30    KBLB    0.1495            3.86   104945     697394      28     qb
30  31   EMHTF    2.8805           -2.65    99025      34150      97     qx
31  32   GGBXF    3.5799            0.85    98481      27377      23     qb
32  33   MMNFF    2.7500            0.00    89120      32275     110     qx
33  34    GBTC    6.6500            0.00    84933      12650      16     qx
34  35   IMBBY   31.9000            0.00    31900       1000      10     qx
35  36    QSEP    0.2500            0.00     8333      33333       1     qb
36  37   VVCIF    0.6149            0.00     6149      10000       1     qx
37  38   FNMAS   11.0800            0.00     4432        400       2     qb
38  39   AVMXY    4.9700            0.00     3492        700       3     qx
39  40   FFMGF    0.2069            0.00     2483      12000       1     qx
40  41   DLAKY   24.4000            0.00     2440        100       1     qx
41  42    WIZP    0.8000            0.00     2400       3000       1     qb
42  43    AITA    2.2200            0.00     2220       1000       3     qb
43  44   OGRMF    7.7500            0.00     1511        195       4     qx
44  45   EMHTF    2.9300            0.00     1467        500       2     qx
45  46   MLRKF    0.0600            0.00      300       5000       1     qx
46  47   NXTTF    0.5246            0.00      262        500       1     qb
47  48    DRNE    1.1300            0.00      226        200       1     qb
48  49   DANOY   16.2200            0.00       16          1       1     qx

In [1]:
"""
for x in range(2):
    html = browser.html
    soup = BeautifulSoup(html,'html.parser')
    
    #divs = browser.find_by_tag("div")
    #browser.click_link_by_partial_text("yi4dEwAzKE")
    #browser.find_link_by_text('yi4dEwAzKE').first.click()
    #browser.find_by_text('MORE').first.click()
    #divs.first.find_by_tag("MORE").first.click()
    
    browser.execute_script("$('body').empty()")
"""

'\nfor x in range(2):\n    html = browser.html\n    soup = BeautifulSoup(html,\'html.parser\')\n    \n    #divs = browser.find_by_tag("div")\n    #browser.click_link_by_partial_text("yi4dEwAzKE")\n    #browser.find_link_by_text(\'yi4dEwAzKE\').first.click()\n    #browser.find_by_text(\'MORE\').first.click()\n    #divs.first.find_by_tag("MORE").first.click()\n    \n    browser.execute_script("$(\'body\').empty()")\n'